config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, skip: [:registrations]
  devise_scope :admin do
    get 'sign_in', to: 'devise/sessions#new'    
  end
  root 'pages#home'
  get '/home', to: 'application#home', as: :home
  resources :gigs, except: :show
  resources :pages, except: :show
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gig.rb
class Gig < ApplicationRecord
  validates :name, :date, presence: :true

  scope :future, -> { where("date > ?", self.yesterday) }

  def date_time
    DateTime.strptime(date, '%m/%d/%Y %l:%M %p')
  end

  def formatted_date
    date_time.strftime('%B %e, %Y')
  end

  private
  
    def self.yesterday
      (DateTime.now - 1.day).strftime('%m/%d/%Y %l:%M %p')
    end
end

app/models/page.rb
class Page < ApplicationRecord
  validates :title, :body, presence: true
  enum status: {
    inactive: 0,
    active: 1      
  }
  scope :active, -> { where(status: "active") }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout 'admin'

  before_action :authenticate_admin!

  def home
    render 'layouts/admin', layout: false
  end
  
  protected

    def after_sign_in_path_for(resource)
      :home
    end
end

app/controllers/gigs_controller.rb
class GigsController < ApplicationController
  before_action :set_gig, only: [:show, :edit, :update, :destroy]

  # GET /gigs
  def index
    @gigs = Gig.all
  end

  # GET /gigs/1
  def show
  end

  # GET /gigs/new
  def new
    @gig = Gig.new
  end

  # GET /gigs/1/edit
  def edit
  end

  # POST /gigs
  def create
    @gig = Gig.new(gig_params)

    if @gig.save
      redirect_to @gig, notice: 'Gig was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /gigs/1
  def update
    if @gig.update(gig_params)
      redirect_to @gig, notice: 'Gig was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /gigs/1
  def destroy
    @gig.destroy
    redirect_to gigs_url, notice: 'Gig was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gig
      @gig = Gig.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def gig_params
      params.require(:gig).permit(:name, :description, :date)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_admin!, only: :home
  before_action :set_page, only: [:show, :edit, :update, :destroy]

  def home
    @gigs = Gig.future
    @pages = Page.active
    render 'layouts/application', layout: false
  end

  def index
    @pages = Page.all
  end

  def new
    @page = Page.new
  end

  def edit
  end

  def create
    @page = Page.new(page_params)

    if @page.save
      redirect_to pages_path, notice: 'page was successfully created.'
    else
      render :new
    end
  end

  def update
    if @page.update(page_params)
      redirect_to pages_path, notice: 'page was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @page.destroy
    redirect_to pages_url, notice: 'page was successfully destroyed.'
  end

  private

    def set_page
      @page = Page.find(params[:id])
      puts @page
    end

    def page_params
      params.require(:page).permit(:body, :title, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gigs_helper.rb
module GigsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/gigs/_form.html.erb
<%= form_with(model: gig, local: true) do |form| %>
  <% if gig.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gig.errors.count, "error") %> prohibited this gig from being saved:</h2>

      <ul>
      <% gig.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control', required: 'true' %>
  </div>

  <div class="field form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :date %>
    <div class='input-group date' id='datetimepicker1'>
      <%= form.text_field :date, class: 'form-control', required: 'true' %>
        <span class="input-group-addon">
            <span class="glyphicon glyphicon-calendar"></span>
        </span>
      </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#datetimepicker1').datetimepicker();
      });
  </script>
  </div>

  <div class="actions">
    <%= form.submit "Submit", class: "btn btn-success" %>
  </div>
<% end %>

app/views/gigs/edit.html.erb
<h1>Editing Gig</h1>

<%= render 'form', gig: @gig %>

<%= link_to 'Show', @gig %> |
<%= link_to 'Back', gigs_path %>

app/views/gigs/index.html.erb
<p id="notice"><%= notice %></p>

<table class="table table-striped">
  <tbody>
    <% @gigs.each do |gig| %>
      <tr>
        <td><strong><%= gig.name %></strong></td>
        <td><%= gig.formatted_date %></td>
        <td class="text-right">
          <%= link_to 'View', gig, class: 'text-primary' %>
          <%= link_to 'Edit', edit_gig_path(gig), class: 'text-success' %>
          <%= link_to 'Delete', gig, 
                      method: :delete,
                      class: 'text-danger',
                      data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
      <tr>
        <td colspan="3" style="padding:1% 10% 5% 10%;"><%= simple_format gig.description %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/gigs/new.html.erb
<h1>New Gig</h1>

<%= render 'form', gig: @gig %>

<%= link_to 'Back', gigs_path %>

app/views/gigs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @gig.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @gig.description %>
</p>

<p>
  <strong>Date:</strong>
  <%= @gig.date %>
</p>

<%= link_to 'Edit', edit_gig_path(@gig) %> |
<%= link_to 'Back', gigs_path %>

app/views/layouts/_about.html.erb
<section id="introduction" class="section introduction">
  <div class="container">
    <div class="row">
        <div class="intro-content">
          <div class="col-md-3 col-sm-12">
            <h1>gigs</h1>
          </div>
          <div class="col-md-9 col-sm-12">
            <ul>
              <% @gigs.each do |gig| %>
                <li>
                  <strong><%= gig.name %></strong> <i><%= gig.formatted_date %></i>
                  <br><small><%= gig.description %></small>
                  <hr>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
</section>

app/views/layouts/_banner.html.erb
<div class="container">
  <div class="col-md-7 banner-inner-wrapper">
    <div class="banner-text">
      <% @pages.each do |page| %>
        <h1><%= page.title %></h1>
        <p><%= simple_format page.body %></p>
      <% end %>
  </div>
</div>

app/views/layouts/_favicon.html.erb
<%= favicon_link_tag "favicon.ico" %>
<!-- iOS and Android -->    
<%= favicon_link_tag "drum-set-silhouette-152-246168.png", rel: "apple-touch-icon-precomposed" %>
<!-- Everything Else -->
<%= favicon_link_tag "drum-set-silhouette-152-246168.png", rel: "apple-touch-icon-precomposed" %>
<%= favicon_link_tag "drum-set-silhouette-144-246168.png", rel: "apple-touch-icon-precomposed" %>
<%= favicon_link_tag "drum-set-silhouette-120-246168.png", rel: "apple-touch-icon-precomposed" %>
<%= favicon_link_tag "drum-set-silhouette-114-246168.png", rel: "apple-touch-icon-precomposed" %>
<%= favicon_link_tag "drum-set-silhouette-72-246168.png", rel: "apple-touch-icon-precomposed" %>
<%= favicon_link_tag "drum-set-silhouette-64-246168.png", rel: "icon",  sizes: "64x64" %>
<%= favicon_link_tag "drum-set-silhouette-32-246168.png" %>
<%= favicon_link_tag "drum-set-silhouette-24-246168.png" %>
<%= favicon_link_tag "drum-set-silhouette-16-246168.png" %>
<%= favicon_link_tag "drum-set-silhouette-57-246168.png", rel: "apple-touch-icon-precomposed" %>
<%= favicon_link_tag "drum-set-silhouette-32-246168.png", rel: "icon" %>

app/views/layouts/_footer.html.erb
<footer id="contact" class="footer">
  <div class="container">
    <div class="col-md-4">
      <h4>Contact</h4>
      <p>contact form goes here</p>
    </div>
    <div class="col-md-4">
      <h4>Social presense</h4>
      <ul class="footer-share">
        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
        <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
        <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
      </ul>
    </div>
    <div class="col-md-4">
      <h4>Links</h4>
      <p>anything else you want here</p>
    </div>
  </div>
</footer>

app/views/layouts/_media.html.erb
<section class="photos">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-4 col-md-3 col-sm-6 photo-container">
       <%= image_tag "20170626_101943.jpg",  alt: "" %>
      </div>
      <div class="col-lg-4 col-md-3 col-sm-6 photo-container">
        <%= image_tag "drumkit.jpg",  alt: "" %>
      </div>
      <div class="col-lg-4 col-md-3 col-sm-6 photo-container">
        <%= image_tag "stage.jpg",  alt: "" %>
      </div>
      <div class="col-lg-4 col-md-3 col-sm-6 photo-container"> 
       <%= image_tag "studio.jpg",  alt: "" %>
      </div>
      <div class="col-lg-4 col-md-3 col-sm-6 photo-container"> 
        <%= image_tag "fire.jpg",  alt: "" %>
        </div>
      <div class="col-lg-4 col-md-3 col-sm-6 photo-container"> 
        <%= image_tag "santa.jpg",  alt: "" %>
      </div>
    </div>
  </div>
</section>

app/views/layouts/_navigation.html.erb
<header id="header">
  <div class="header-content clearfix">
    <a class="logo" href="#">Lynn Farmer</a>
    <nav class="navigation" role="navigation">
    <ul class="primary-nav">
        <li><a href="#introduction">Gigs</a></li>
        <li><a href="#works">Latest Works</a></li>
        <li><a href="#contact">Contact Me</a></li>
      </ul>
    </nav>
    <a href="#" class="nav-toggle">Menu<span></span></a>
  </div>
</header>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>Lynn Farmer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class='container' id='admin-container'>

    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><%= link_to "Home", home_path %></li>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Pages <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li>
                  <%= link_to "All Pages", pages_path %>
                </li>
                <li><%= link_to "New Page", new_page_path %></li>
              </ul>
            </li>
          </ul>
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Gigs <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li>
                  <%= link_to "All Gigs", gigs_path %>
                </li>
                <li><%= link_to "New Gig", new_gig_path %></li>
              </ul>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "View Site", root_path %></li>
            <li>
              <%= link_to 'Sign out', destroy_admin_session_path, method: :delete %>  
            </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    <%= yield %>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
  <!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
  <!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
  <!--[if gt IE 8]><!-->
  <html class="no-js" lang="">
  <!--<![endif]-->

  <head>
    <title>Lynn Farmer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= render 'layouts/favicon' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%# theme forked from DesignStubs Floix theme %>
  </head>

  <body>
    <section class="banner" role="banner"> 
      <%= render 'layouts/navigation' %>
      <%= render 'layouts/banner' %>
    </section>

    <%= render 'layouts/about' %>

    <%= render 'layouts/media' %>

    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/_form.html.erb
<%= form_with(model: page, local: true) do |form| %>
  <% if page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control', required: 'true' %>
  </div>

  <div class="field form-group">
    <%= form.label :body %>
    <%= form.text_area :body, rows: 14, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :status %>
    <%= form.select :status,
        options_for_select( Page.statuses.keys ),
        {},
        class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit "Submit", class: "btn btn-success" %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing Page</h1>

<%= render 'form', page: @page %>

<br><%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<p id="notice"><%= notice %></p>

<table class="table table-striped">
  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td>
          <strong>(<%= page.status %>)</strong>
        </td>
        <td>
          <%= page.title %>
        </td>
        <td class="text-right">
          <%= link_to 'Edit', edit_page_path(page), class: 'text-success' %>
          <%= link_to 'Delete', page, 
              method: :delete, 
              class: 'text-danger',
              data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
      <tr>
        <td colspan="3" style="padding:1% 10% 5% 10%;">
          <%= simple_format page.body %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/pages/new.html.erb
<h1>New Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>